// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: agent.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentClient interface {
	InitInstance(ctx context.Context, in *InitInstanceRequest, opts ...grpc.CallOption) (Agent_InitInstanceClient, error)
	BuildAndStartDevEnv(ctx context.Context, in *BuildAndStartDevEnvRequest, opts ...grpc.CallOption) (Agent_BuildAndStartDevEnvClient, error)
}

type agentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentClient(cc grpc.ClientConnInterface) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) InitInstance(ctx context.Context, in *InitInstanceRequest, opts ...grpc.CallOption) (Agent_InitInstanceClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[0], "/agent.Agent/InitInstance", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentInitInstanceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Agent_InitInstanceClient interface {
	Recv() (*InitInstanceReply, error)
	grpc.ClientStream
}

type agentInitInstanceClient struct {
	grpc.ClientStream
}

func (x *agentInitInstanceClient) Recv() (*InitInstanceReply, error) {
	m := new(InitInstanceReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *agentClient) BuildAndStartDevEnv(ctx context.Context, in *BuildAndStartDevEnvRequest, opts ...grpc.CallOption) (Agent_BuildAndStartDevEnvClient, error) {
	stream, err := c.cc.NewStream(ctx, &Agent_ServiceDesc.Streams[1], "/agent.Agent/BuildAndStartDevEnv", opts...)
	if err != nil {
		return nil, err
	}
	x := &agentBuildAndStartDevEnvClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Agent_BuildAndStartDevEnvClient interface {
	Recv() (*BuildAndStartDevEnvReply, error)
	grpc.ClientStream
}

type agentBuildAndStartDevEnvClient struct {
	grpc.ClientStream
}

func (x *agentBuildAndStartDevEnvClient) Recv() (*BuildAndStartDevEnvReply, error) {
	m := new(BuildAndStartDevEnvReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AgentServer is the server API for Agent service.
// All implementations must embed UnimplementedAgentServer
// for forward compatibility
type AgentServer interface {
	InitInstance(*InitInstanceRequest, Agent_InitInstanceServer) error
	BuildAndStartDevEnv(*BuildAndStartDevEnvRequest, Agent_BuildAndStartDevEnvServer) error
	mustEmbedUnimplementedAgentServer()
}

// UnimplementedAgentServer must be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (UnimplementedAgentServer) InitInstance(*InitInstanceRequest, Agent_InitInstanceServer) error {
	return status.Errorf(codes.Unimplemented, "method InitInstance not implemented")
}
func (UnimplementedAgentServer) BuildAndStartDevEnv(*BuildAndStartDevEnvRequest, Agent_BuildAndStartDevEnvServer) error {
	return status.Errorf(codes.Unimplemented, "method BuildAndStartDevEnv not implemented")
}
func (UnimplementedAgentServer) mustEmbedUnimplementedAgentServer() {}

// UnsafeAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentServer will
// result in compilation errors.
type UnsafeAgentServer interface {
	mustEmbedUnimplementedAgentServer()
}

func RegisterAgentServer(s grpc.ServiceRegistrar, srv AgentServer) {
	s.RegisterService(&Agent_ServiceDesc, srv)
}

func _Agent_InitInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).InitInstance(m, &agentInitInstanceServer{stream})
}

type Agent_InitInstanceServer interface {
	Send(*InitInstanceReply) error
	grpc.ServerStream
}

type agentInitInstanceServer struct {
	grpc.ServerStream
}

func (x *agentInitInstanceServer) Send(m *InitInstanceReply) error {
	return x.ServerStream.SendMsg(m)
}

func _Agent_BuildAndStartDevEnv_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BuildAndStartDevEnvRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentServer).BuildAndStartDevEnv(m, &agentBuildAndStartDevEnvServer{stream})
}

type Agent_BuildAndStartDevEnvServer interface {
	Send(*BuildAndStartDevEnvReply) error
	grpc.ServerStream
}

type agentBuildAndStartDevEnvServer struct {
	grpc.ServerStream
}

func (x *agentBuildAndStartDevEnvServer) Send(m *BuildAndStartDevEnvReply) error {
	return x.ServerStream.SendMsg(m)
}

// Agent_ServiceDesc is the grpc.ServiceDesc for Agent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Agent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agent.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InitInstance",
			Handler:       _Agent_InitInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "BuildAndStartDevEnv",
			Handler:       _Agent_BuildAndStartDevEnv_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}
